// Shared option constants for forms

export const POSTES_EMPLOI = [
  "Ingénieur",
  "Magasinier",
  "Auditeur",
  "Contrôleur de gestion",
  "Comptable",
  "Assistant comptable",
  "Technicien",
  "Développeur",
  "Designer",
  "Commercial",
  "Responsable RH",
  "Chargé de recrutement",
  "Chef de projet",
  "Data Analyst",
  "Data Scientist",
  "UX/UI Designer",
  "Support IT",
  "Logisticien",
  "Opérateur de production",
  "Agent de maintenance",
  "Responsable qualité",
  "Sécurité",
  "Médecin",
  "Infirmier",
  "Formateur",
  "Juriste",
  "Chargé de communication",
  "Community Manager",
  "Trésorier",
  "Caissier",
  "Secrétaire",
  "Assistant de direction",
  "Stagiaire",
  "Apprenti",
];

export const CATEGORIES_PROFESSIONNELLES = [
  "Cadre supérieur",
  "Cadre moyen",
  "Agent de maîtrise",
  "Employé",
  "Ouvrier qualifié",
  "Ouvrier non qualifié",
  "Technicien",
  "Ingénieur",
  "Agent commercial",
  "Stagiaire",
  "Apprenti",
];

export const DEPARTEMENTS = [
  "Direction générale",
  "Direction administrative",
  "Direction financière",
  "Direction des ressources humaines",
  "Direction commerciale",
  "Direction marketing",
  "Direction informatique",
  "Direction logistique",
  "Direction de production",
  "Direction maintenance",
  "Direction qualité",
  "Direction sécurité",
  "Direction médicale",
  "Direction formation",
  "Direction communication",
  "Direction juridique",
  "Direction audit",
  "Direction recherche",
  "Direction développement",
  "Direction support",
  "Direction data",
  "Direction engineering",
  "Direction opérations",
  "Direction comptable",
  "Direction approvisionnement",
  "Direction achats",
  "Direction import/export",
  "Direction relations publiques",
  "Direction partenariats",
  "Direction client",
  "Direction service après-vente",
  "Direction production agroalimentaire",
  "Direction production textile",
  "Direction production énergétique",
  "Direction artisanat",
  "Direction BTP",
  "Direction transport",
  "Direction tourisme",
  "Direction hôtellerie",
  "Direction restauration",
  "Direction éducation",
  "Direction recherche scientifique",
  "Direction environnement",
  "Direction agriculture",
  "Direction élevage",
  "Direction pêche",
  "Direction mines",
  "Direction pétrole et gaz",
  "Direction télécommunications",
  "Direction médias",
  "Direction culture",
  "Direction sport",
  "Direction événementiel",
  "Direction ONG",
  "Direction administration publique",
  "Direction collectivités territoriales",
  "Direction santé",
  "Direction assurances",
  "Direction banques",
  "Direction microfinance",
  "Direction immobilier",
  "Direction transport et logistique",
  "Direction export",
  "Direction import",
  "Direction expert-comptable",
  "Direction commissaire aux comptes",
  "Direction actuaire",
  "Direction statisticien",
  "Direction économiste",
  "Direction sociologue",
  "Direction psychologue",
  "Direction travailleur social",
  "Direction éducateur",
  "Direction animateur socioculturel",
  "Direction journaliste",
  "Direction rédacteur",
  "Direction traducteur",
  "Direction interprète",
  "Direction photographe",
  "Direction vidéaste",
  "Direction monteur",
  "Direction graphiste",
  "Direction web designer",
  "Direction UX/UI Designer",
  "Direction sound designer",
  "Direction architecte d'information",
  "Direction product manager",
  "Direction scrum master",
  "Direction agile coach",
  "Direction business analyst",
  "Direction data analyst",
  "Direction data scientist",
  "Direction data engineer",
  "Direction machine learning engineer",
  "Direction AI engineer",
  "Direction DevOps engineer",
  "Direction site reliability engineer",
  "Direction cloud engineer",
  "Direction infrastructure engineer",
  "Direction network engineer",
  "Direction cybersecurity engineer",
  "Direction database administrator",
  "Direction system administrator",
  "Direction technical lead",
  "Direction engineering manager",
  "Direction CTO",
  "Direction CIO",
  "Direction CFO",
  "Direction COO",
  "Direction CEO",
];

export const CATEGORIES_CNPS = [
  "Catégorie 1",
  "Catégorie 2",
  "Catégorie 3",
  "Catégorie 4",
  "Catégorie 5",
  "Catégorie 6",
  "Catégorie 7",
  "Catégorie 8",
  "Catégorie 9",
  "Catégorie 10",
  "Catégorie 11",
  "Catégorie 12",
];

export const ECHELONS_CNPS = [
  "Échelon A",
  "Échelon B",
  "Échelon C",
  "Échelon D",
  "Échelon E",
  "Échelon F",
  "Échelon G",
];

export const DIPLOMES = [
  "Sans diplôme",
  "CEP",
  "BEPC",
  "Baccalauréat",
  "BTS",
  "DUT",
  "Licence",
  "Maîtrise",
  "Master",
  "Doctorat",
  "Ingénieur",
  "Architecte",
  "Médecin",
  "Pharmacien",
  "Avocat",
  "Notaire",
  "Expert-comptable",
  "Formation professionnelle",
  "Certification",
  "Autre",
];

export const SERVICES = [
  "Service administratif",
  "Service technique",
  "Service commercial",
  "Service financier",
  "Service RH",
  "Service marketing",
  "Service informatique",
  "Service logistique",
  "Service production",
  "Service maintenance",
  "Service qualité",
  "Service sécurité",
  "Service médical",
  "Service formation",
  "Service communication",
  "Service juridique",
  "Service audit",
  "Service recherche",
  "Service développement",
  "Service support",
];

export const SITUATIONS_FAMILLE = [
  "Célibataire",
  "Marié(e)",
  "Divorcé(e)",
  "Veuf/Veuve",
  "Concubinage",
  "PACS",
];

// Cameroon cities and neighborhoods
export const VILLES_CAMEROUN = [
  "Douala", "Yaoundé", "Garoua", "Bamenda", "Maroua", "Bafoussam", "Ngaoundéré", "Bertoua", "Ebolowa", "Kumba"
];

export const QUARTIERS_PAR_VILLE = {
  Douala: ["Akwa", "Bonapriso", "Bonamoussadi", "Deido", "Makepe", "Logbaba", "Bali", "New Bell", "Cité des Palmiers", "Bonabéri"],
  Yaoundé: ["Bastos", "Melen", "Mvog Ada", "Nlongkak", "Essos", "Emana", "Mokolo", "Biyem-Assi", "Etoudi", "Ekounou"],
};
